# Generated by Django 4.2 on 2023-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peruntukan', models.CharField(max_length=255)),
                ('Pusat_kota', models.CharField(max_length=255)),
                ('Visibilitas', models.CharField(max_length=255)),
                ('Bangunan', models.CharField(max_length=255)),
                ('Luas', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peruntukan', models.CharField(max_length=255)),
                ('Pusat_kota', models.CharField(max_length=255)),
                ('Visibilitas', models.CharField(max_length=255)),
                ('Bangunan', models.CharField(max_length=255)),
                ('Luas', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20)),
            ],
        ),
    ]
