# Generated by Django 4.2 on 2023-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingdata',
            name='Deskripsi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='Deskripsi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
